name: quadrapassel
version: 3.22.0
summary: Fit falling blocks together
description: |
  Quadrapassel is a derivative of a classic Russian falling-block game.
  Reposition and rotate the blocks as they fall, and attempt to fit them
  together. When you form a complete horizontal row of blocks, the row will
  disappear and you score points. The game is over when the blocks get stacked
  too high. As your score gets higher, you level up and the blocks fall faster.

  If you're looking for a challenge, Quadrapassel allows you to increase the
  initial speed of the blocks, or begin the game with partial blocks on some
  of the rows. Or, instead of allowing the blocks to fall randomly, it can
  select blocks that will be hard for you to place.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
    gnome-3-24-platform:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-24:gnome-3-24-platform

slots:
  # for GtkApplication registration
  quadrapassel:
    interface: dbus
    bus: session
    name: org.gnome.quadrapassel

apps:
  quadrapassel:
    command: desktop-launch quadrapassel
    plugs:
      - network
      - x11
      - home
      - gsettings
      - unity7
    desktop: usr/share/applications/quadrapassel.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/quadrapassel

parts:
  desktop-gnome-platform:
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform

  quadrapassel:
    source: https://git.gnome.org/browse/quadrapassel
    source-type: git
    #source-branch: master
    source-tag: 3.22.0
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/quadrapassel/current/usr]
    organize:
      snap/quadrapassel/current/usr: usr
    prepare: |
      apt install software-properties-common
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-24
      apt update
      sed -i.bak -e 's|=quadrapassel$|=${SNAP}/meta/gui/quadrapassel.png|g' data/quadrapassel.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/quadrapassel.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/quadrapassel.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - gsettings-desktop-schemas-dev
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libcanberra-gtk3-dev
      - libclutter-1.0-dev
      - libclutter-gtk-1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - valac
      - yelp-tools

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
